"""Build local UI fonts from official Google Fonts sources (fonttools + brotli).

Run from any directory with --source-dir pointing to NotoSansSC.ttf and Manrope.ttf.
The build pipeline uses the checked-in WOFF2 files; Python is maintenance-only.
"""
import argparse
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--source-dir', type=Path, required=True)
args = parser.parse_args()
frontend = Path(__file__).resolve().parents[1]
destination = frontend / 'public/fonts'
destination.mkdir(parents=True, exist_ok=True)

# Only fixed application copy is scanned. User content always retains system fallbacks.
copy = ''.join(p.read_text(encoding='utf-8') for p in (frontend / 'src').rglob('*')
               if p.suffix in {'.vue', '.js', '.css'})
cjk = {ord(c) for c in copy if ord(c) >= 0x2000}
latin = set(range(0x20, 0x100)) | set(range(0x2000, 0x2070)) | {0x20ac, 0x2122, 0x2190, 0x2192}

for source, target, chars in [
    ('NotoSansSC.ttf', 'noto-sans-sc-ui.woff2', cjk),
    ('Manrope.ttf', 'manrope-latin.woff2', latin),
]:
    options = subset.Options()
    options.flavor = 'woff2'
    options.name_IDs = ['*']
    options.name_legacy = True
    options.name_languages = ['*']
    font = TTFont(args.source_dir / source, recalcTimestamp=False)
    available = set(font.getBestCmap())
    selected = chars & available
    worker = subset.Subsetter(options=options)
    worker.populate(unicodes=selected)
    worker.subset(font)
    font.flavor = 'woff2'
    font.save(destination / target)
    print(f'{target}: {len(selected)} characters, {(destination / target).stat().st_size:,} bytes')

    # Let browsers skip the Chinese face for Latin and missing characters.
    if source == 'NotoSansSC.ttf':
        ranges = ', '.join(f'U+{code:X}' for code in sorted(selected))
        (frontend / 'src/font-faces.css').write_text(
            '/* Generated by scripts/subset-fonts.py. Licenses: public/fonts/*-OFL.txt */\n'
            '@font-face {\n  font-family: "Noto Sans SC UI";\n'
            '  src: url("/fonts/noto-sans-sc-ui.woff2") format("woff2");\n'
            '  font-style: normal;\n  font-weight: 100 900;\n  font-display: swap;\n'
            f'  unicode-range: {ranges};\n}}\n\n'
            '@font-face {\n  font-family: "Manrope";\n'
            '  src: url("/fonts/manrope-latin.woff2") format("woff2");\n'
            '  font-style: normal;\n  font-weight: 200 800;\n  font-display: swap;\n'
            '  unicode-range: U+20-FF, U+2000-206F, U+20AC, U+2122, U+2190, U+2192;\n}\n',
            encoding='utf-8',
        )
